### ISSUE TITLE
use miniforge to install conda base environment

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks-dev#14]
Following @yuvipanda 's lead in https://github.com/jupyter/repo2docker/pull/859 
> miniforge is a new community-led installer that uses conda-forge as the default
channel, rather than defaults. So no mixing of defaults & conda-forge channel by default. and would likely reduce image size.

@TomAugspurger also looked into using just the conda standalone executable since we don't really need a (base) environment, but it is what people are used to locally, so I think it is worth keeping.
https://github.com/TomAugspurger/pangeo2docker/blob/f687f97dcf8f48d34033ea1903befd12d578f659/pangeo2docker/Dockerfile.tpl#L25

**Comment by scottyhq** [comment]
Doing some quick local tests of this I'm not noticing reductions in image size. I think this is because not all packages in the root environment are linked in new environments https://github.com/conda/conda/issues/4881

**Comment by jhamman** [comment]
> @TomAugspurger also looked into using just the conda standalone executable since we don't really need a (base) environment, but it is what people are used to locally, so I think it is worth keeping.

I don't think most people know there are multiple environments and it isn't part of the r2d spec in any way (afaik). I think I've said this before but I don't think we need to maintain this feature (which is really a workaround on the r2d side).

**Comment by scottyhq** [comment]
@jhamman  I like keeping the (base) + (otherenvs) structure since I'm accustomed to it working locally, and I was hoping we'd be able to reuse the same python version to save space, but that doesn't seem to be the case for now https://github.com/conda-forge/miniforge/issues/21#issuecomment-595338583 

These standalone conda executables (https://repo.anaconda.com/pkgs/misc/conda-execs/) do not come with the `conda env` command, and do not have the same initialization scripts. Maybe just putting the standalone conda executable in the PATH is enough though... The main issue is without `conda env` you can't use environment.yml files. So one option is to stick with the more flexible `conda create` and use  to convert any environment.yml files into pkgs.txt. See  https://github.com/pangeo-data/pangeo-stacks-dev/issues/15
