### ISSUE TITLE
Review of Dockerfile cleanup commands

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks-dev#22]
Currently we are running a lot of custom cleanup commands to save space on the images:
https://github.com/pangeo-data/pangeo-stacks-dev/blob/899e2e7bcc76354f1d4b584dc21742492cd81325/base-image/Dockerfile#L92-L96

I just ran into an error where one of the commands failed, possibly related to a change in layout with bokeh 2.0. cc @TomAugspurger . I'll go ahead and comment it out for now
```
bokeh-2.0.0          | 6.8 MB    | ########## | 100%
find: ‘/srv/conda/envs/pangeo/lib/python*/site-packages/bokeh/server/static’: No such file or directory
```

**Comment by TomAugspurger** [comment]
That's strange. Does the `/srv/conda/envs/pangeo/` part look correct? Locally my copy of `bokeh` still has the same `/bokeh/server/static` layout.

**Comment by scottyhq** [comment]
Actually, the error was because I had a name other than 'pangeo' in an environment.yml :
```
name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.03.27
  - xarray
  - hvplot
  - pip
  - pip:
    - sat-search
```

Easy fix by forcing the name pangeo in the Dockerfile:
https://github.com/pangeo-data/pangeo-stacks-dev/blob/899e2e7bcc76354f1d4b584dc21742492cd81325/base-image/Dockerfile#L88

`conda env create --name pangeo -f environment.yml`

**Comment by TomAugspurger** [comment]
👍 we probably want that.

Do you have thoughts on naming it `pangeo` vs `notebook`? I wonder how many postBuild scripts out there are hardcoding `notebook` there, since that's what repo2docker uses?

**Comment by tjcrone** [comment]
I think I would vote for notebook.

**Comment by scottyhq** [comment]
ok. also +1 on notebook. note sure why i started with pangeo. best to keep as close as possible to repo2docker. about to push a PR that will fix this.
