### ISSUE TITLE
Add bot to create PR when metapackage versions change

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks-dev#26]
As suggested in https://github.com/pangeo-gallery/default-binder/pull/1

We should have an Action that creates a PR whenever a new `pangeo-notebook` metapackage becomes available.
https://github.com/conda-forge/pangeo-notebook-feedstock

For example we could bump each image to go from `2020.03.27` --> `2020.03.30`

**Comment by TomAugspurger** [comment]
What order do updates need to happen in?

- Update to dask (outside pangeo's control)
-> Update to pangeo-dask-feedstock
-> update to pangeo-notebook-feedstock
-> update to pangeo-stacks-dev

Is that everything?
